refactor: Header component
carlosalbertojusto/MovieBox pull request #6
Opened 2023-04-15 17:12 UTC by carlosalbertojusto

Componente para o Header foi criado, começo da function para a paginação

2023-04-17 23:52 UTC, milealmeida commented on src/components/PaginationBox/index.jsx
> +        {" "}
Adiciona espaço com css, esse { " "} não fica muito elegante

2023-04-17 23:53 UTC, milealmeida commented on src/components/PaginationBox/styles.js
> +  > button {
Não precisa do >

2023-04-17 23:56 UTC, milealmeida commented on src/pages/Home/index.jsx
> +      if (pagination == id) {
Trocar para ===. 
'1'== 1 => true, ele só compara se os valores são iguais, independente se é string com number e etc;
'1'=== 1 => false, compara se a até o tipo do valor é igual, é uma melhor prática

2023-04-17 23:59 UTC, milealmeida commented on src/pages/Home/index.jsx
> +  function handlePagination(e) {
Aonde o "e"está sendo utilizado?

2023-04-18 00:00 UTC, milealmeida commented on src/pages/Home/index.jsx
> +        onClick={(e) => handlePagination()}
O "e" aparentemente não está sendo utilizado, pode chamar o handlePagination direto

2023-04-18 00:01 UTC, milealmeida requested changes
Code review realizado

2023-04-18 00:02 UTC, carlosalbertojusto commented on src/pages/Home/index.jsx
> +      if (pagination == id) {
sim vou fazer as alterações nessa function pq percebi que estava fazendo algo totalmente errado no setPagination

2023-04-18 00:03 UTC, carlosalbertojusto commented on src/pages/Home/index.jsx
> +  function handlePagination(e) {
tava passando o event.target.value por ele antes de apagar metade da função que não tava funcionando

2023-04-18 00:04 UTC, carlosalbertojusto commented on src/components/PaginationBox/index.jsx
> +        {" "}
isso daqui foi o prettier que colocou eu esqueci de remover

2023-04-19 22:37 UTC, milealmeida approved these changes

2023-04-19 22:42 UTC, merged